from nonebot.adapters.onebot.v11 import Bot
from nonebot.adapters.onebot.v11.event import MessageEvent
from nonebot.adapters.onebot.v11.message import Message
from nonebot.params import CommandArg
from nonebot.plugin import on_command

profile_command = on_command("profile", aliases={"资料卡"}, priority=5, block=False)


@profile_command.handle()
async def _(bot: Bot, event: MessageEvent, arg: Message = CommandArg()):
    # b = await bot.get_stranger_info(user_id=event.user_id)
    ...
    # aaa = {
    #     "uid": "u_LqYEiOp8d_CR7FrilBQM9w",
    #     "uin": "1479559098",
    #     "nick": "SakuraiCora",
    #     "remark": "",
    #     "constellation": 0,
    #     "shengXiao": 0,
    #     "kBloodType": 0,
    #     "homeTown": "0-0-0",
    #     "makeFriendCareer": 10,
    #     "pos": "",
    #     "college": "",
    #     "country": "",
    #     "province": "",
    #     "city": "",
    #     "postCode": "",
    #     "address": "",
    #     "regTime": 1262354862,
    #     "interest": "",
    #     "labels": [],
    #     "qqLevel": 59,
    #     "qid": "",
    #     "longNick": "Never give up!",
    #     "birthday_year": 2002,
    #     "birthday_month": 4,
    #     "birthday_day": 10,
    #     "age": 22,
    #     "sex": "female",
    #     "eMail": "sakuraicora@gmail.com",
    #     "phoneNum": "-",
    #     "categoryId": 0,
    #     "richTime": 1518192157,
    #     "richBuffer": {
    #         "0": 3,
    #         "1": 14,
    #         "2": 78,
    #         "3": 101,
    #         "4": 118,
    #         "5": 101,
    #         "6": 114,
    #         "7": 32,
    #         "8": 103,
    #         "9": 105,
    #         "10": 118,
    #         "11": 101,
    #         "12": 32,
    #         "13": 117,
    #         "14": 112,
    #         "15": 33,
    #         "16": 145,
    #         "17": 4,
    #         "18": 0,
    #         "19": 0,
    #         "20": 0,
    #         "21": 0,
    #         "22": 146,
    #         "23": 4,
    #         "24": 0,
    #         "25": 0,
    #         "26": 0,
    #         "27": 0,
    #         "28": 144,
    #         "29": 28,
    #         "30": 49,
    #         "31": 52,
    #         "32": 55,
    #         "33": 57,
    #         "34": 53,
    #         "35": 53,
    #         "36": 57,
    #         "37": 48,
    #         "38": 57,
    #         "39": 56,
    #         "40": 49,
    #         "41": 100,
    #         "42": 99,
    #         "43": 54,
    #         "44": 55,
    #         "45": 100,
    #         "46": 53,
    #         "47": 97,
    #         "48": 102,
    #         "49": 102,
    #         "50": 98,
    #         "51": 56,
    #         "52": 48,
    #         "53": 101,
    #         "54": 48,
    #         "55": 48,
    #         "56": 102,
    #         "57": 56,
    #     },
    #     "topTime": "0",
    #     "isBlock": False,
    #     "isMsgDisturb": False,
    #     "isSpecialCareOpen": False,
    #     "isSpecialCareZone": False,
    #     "ringId": "",
    #     "isBlocked": False,
    #     "recommendImgFlag": 1,
    #     "disableEmojiShortCuts": 1,
    #     "qidianMasterFlag": 0,
    #     "qidianCrewFlag": 0,
    #     "qidianCrewFlag2": 0,
    #     "isHideQQLevel": 0,
    #     "isHidePrivilegeIcon": 1,
    #     "status": 20,
    #     "extStatus": 0,
    #     "batteryStatus": 0,
    #     "termType": 0,
    #     "netType": 0,
    #     "iconType": 0,
    #     "customStatus": None,
    #     "setTime": "0",
    #     "specialFlag": 0,
    #     "abiFlag": 0,
    #     "eNetworkType": 0,
    #     "showName": "",
    #     "termDesc": "",
    #     "musicInfo": {"buf": {}},
    #     "extOnlineBusinessInfo": {
    #         "buf": {},
    #         "customStatus": None,
    #         "videoBizInfo": {"cid": "", "tvUrl": "", "synchType": ""},
    #         "videoInfo": {"name": ""},
    #     },
    #     "extBuffer": {"buf": {}},
    #     "user_id": 1479559098,
    #     "nickname": "SakuraiCora",
    #     "long_nick": "Never give up!",
    #     "reg_time": 1262354862,
    #     "is_vip": False,
    #     "is_years_vip": False,
    #     "vip_level": 0,
    #     "login_days": 0,
    # }
    # # TODO
